Repository GaspardCulis/robot-rumble-rs, pull requests merged in 2025-06, with the labels that each got.

#49 Dev/level editor
  .gitignore
  Cargo.lock
  Cargo.toml
  src/core/collision.rs
  src/core/worldgen.rs
  src/entities/planet/materials/mod.rs
  src/entities/planet/mod.rs
  src/entities/satellite/grabber.rs
  src/entities/satellite/mod.rs
  src/level/limit.rs
  src/level/mod.rs
  src/level/save.rs
  src/lib.rs
  src/main.rs
  src/network/mod.rs
  src/tools/map_editor/controller.rs
  src/tools/map_editor/interaction.rs
  src/tools/map_editor/main.rs
  src/tools/map_editor/model.rs
  src/tools/map_editor/utils.rs
  src/tools/map_editor/view.rs
Labels: enhancement

#47 Feat/blackhole
  assets/config/projectiles.ron
  assets/config/weapons.ron
  assets/shaders/planet/black_hole.wgsl
  assets/shaders/planet/black_hole_ring.wgsl
  assets/weapons/blackhole_gun.png
  src/entities/blackhole/mod.rs
  src/entities/blackhole/visuals.rs
  src/entities/mod.rs
  src/entities/planet/mod.rs
  src/entities/player/inventory.rs
  src/entities/player/weapon/config.rs
  src/entities/player/weapon/mod.rs
  src/entities/projectile/config.rs
  src/entities/projectile/mod.rs
  src/network/mod.rs
Labels: enhancement

#61 Feat/asset loading state
  Cargo.lock
  Cargo.toml
  assets/config/config.planets.ron
  assets/config/config.projectiles.ron
  assets/config/config.satellites.ron
  assets/config/config.weapons.ron
  assets/config/config.worldgen.ron
  assets/config/skins.ron
  assets/config/skins/laika.skin.ron
  src/assets.rs
  src/core/worldgen.rs
  src/entities/planet/mod.rs
  src/entities/player/animation.rs
  src/entities/player/inventory.rs
  src/entities/player/mod.rs
  src/entities/player/skin.rs
  src/entities/player/weapon/config.rs
  src/entities/player/weapon/mod.rs
  src/entities/projectile/config.rs
  src/entities/projectile/mod.rs
  src/entities/satellite/assets.rs
  src/entities/satellite/bumper.rs
  src/entities/satellite/grabber.rs
  src/entities/satellite/graviton.rs
  src/entities/satellite/mod.rs
  src/level/limit.rs
  src/lib.rs
  src/main.rs
Labels: enhancement

#77 Chore/self hosted turn
  src/network/mod.rs
Labels: Networking

#79 feat(camera): made camera follow multiple players at a time with bounding logic.
  src/core/camera.rs
Labels: feature

#81 Refactor home ui with `bevy_cobweb_ui`
  Cargo.lock
  Cargo.toml
  assets/ui/main.cob
  assets/ui/menu/home.cob
  src/ui/menus/home.rs
  src/ui/menus/mod.rs
  src/ui/mod.rs
  src/ui/widgets/mod.rs
Labels: scope:ui

#67 Feat/UI home menu
  Cargo.lock
  Cargo.toml
  assets/img/backgrounds/terrorist-dog.webp
  assets/ui/main.cob
  assets/ui/menu/home.cob
  src/assets.rs
  src/lib.rs
  src/main.rs
  src/ui/menus/home.rs
  src/ui/menus/mod.rs
  src/ui/mod.rs
Labels: type:feature, scope:ui

#46 Feat/graviton update
  assets/config/config.satellites.ron
  assets/img/satellites/destroyed_slingshot.png
  assets/img/satellites/slingshot/rope_1.png
  assets/img/satellites/slingshot/rope_2.png
  assets/img/satellites/slingshot/rope_3.png
  assets/img/satellites/slingshot/rope_4.png
  assets/img/satellites/working_slingshot.png
  src/core/worldgen.rs
  src/entities/player/mod.rs
  src/entities/satellite/assets.rs
  src/entities/satellite/graviton.rs
  src/entities/satellite/mod.rs
  src/entities/satellite/slingshot.rs
  src/network/mod.rs
  src/tools/map_editor/controller.rs
  src/tools/map_editor/view.rs
Labels: type:feature, scope:gameplay, prio:high
